basePath: /api
definitions:
  dto.UserDto:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
host: localhost:8585
info:
  contact: {}
  description: GoTemplate API
  title: GoTemplate API
  version: "1.0"
paths:
  /v1/sample/hello-world:
    get:
      consumes:
      - application/json
      description: Get a hello world string
      operationId: get-hello-world
      produces:
      - application/json
      responses: {}
      summary: Get a hello world string
      tags:
      - sample
  /v1/sample/users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      operationId: get-user-by-id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDto'
      summary: Get a user by ID
      tags:
      - sample
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
